selectTemplate('Oracle Traffic Director - Restricted JRF')
loadTemplates()
cd('Servers/AdminServer')
set('ListenAddress','localhost')
set('ListenPort',7001)
cd('/')
cd('Security/base_domain/User/weblogic')
cmo.setPassword('otd123otd')
setOption('OverwriteDomain','true')
writeDomain('/home/openlabsummerstudent/Oracle/user_projects/domains/otd_domain')
closeTemplate()
exit('y')
